#pragma once

#include <thread>
#include <numeric>
#include <future>
#include <random>
#include <iterator>
#include <boost/algorithm/string.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/path.hpp>
#include "ASSERT_TRACE_VERIFY.h"
#include "HelperFunctions.h"
#include "IFitness.h"
#include "FitnessFromMathExpression.h"
#include "ParamsES.h"
#include "ParamsIndividual.h"
#include "ISortedFitnessTable.h"
#include "SortedFitnessTable.h"
#include "RandNumbersGenerator.h"
#include "Mutation.h"
#include "Recombination.h"
#include "Selection.h"
#include "ParamsESGB.h"
#include "Optimizer.h"
#include "OptimizerES.h"
#include "OptimizerESGB.h"
#include "OptimizerESP.h"
#include "ESsettingsFileInteractor.h"
#include "EngineGeneratorESGB.h"
#include "EngineGeneratorESP.h"
#include "OptimizerFactory.h"